### ISSUE TITLE
Actually running in afterRender

### ISSUE THREAD

**Issue by nathanhammond** [trentmwillis/ember-axe#2]
I believe that this is less likely to need to capture literally every flush of the `render` (sub)queue and could instead run inside of `afterRender`.

``` js
Ember.scheduleOnce('afterRender', this, axe.ember.afterRender);
```

**Comment by trentmwillis** [comment]
I agree that cutting down on the number of times it runs would be beneficial, but I don't think this will have the intended result. My understanding is that `scheduleOnce` will only schedule it for the specified queue in the current run-loop. Once that run-loop is over, it won't execute anymore.

I originally thought that maybe we could create a loop of scheduling callbacks, but I believe that would just leave us with a never ending run-loop.

Thoughts?

**Comment by nathanhammond** [comment]
@asakusuma monkeypatched the run loop where if during a particular run loop the `render` subqueue was flushed then it ran a function at the run loop's completion. Not terrible. ;)

What if you instead just generically hooked the end of each run loop? Guaranteed to have settled at that point, runs once per run loop ... often enough?

**Comment by asakusuma** [comment]
Here is the code Nathan is talking about: https://gist.github.com/asakusuma/07dc535034152e1277fc

**Comment by trentmwillis** [comment]
Awesome, thank Asa.

@nathanhammond how would I generically hook into the end of each run-loop? Set `Ember.run.backburner.options.onEnd`?

**Comment by nathanhammond** [comment]
Yep, that's what I was thinking.

**Comment by nathanhammond** [comment]
Closed as part of the migration to [ember-a11y-testing](https://github.com/trentmwillis/ember-a11y-testing).
