### ISSUE TITLE
Improve logging and debugging of violations

### ISSUE THREAD

**Issue by trentmwillis** [trentmwillis/ember-axe#3]
Initial implementation of logging for the audits has been minimal. Currently, it just outputs the violations in numeric order follow by a dump of the object. Example:

![screen shot 2015-06-25 at 10 10 41 pm](https://cloud.githubusercontent.com/assets/3526753/8371154/fee50ac8-1b87-11e5-94e7-34831424965e.png)

This isn't the worst, but can definitely be made better before the official 1.0 release. Following are proposed features for better logging of violations (subject to change):

**General Improvements**
- [ ] Present information in an easy-to-digest format before dumping the object.
  - Potential format: `[impact]: [help]. Offending markup is: [nodes.html].`
  - Ex: `CRITICAL: Form elements must have labels. Offending markup is: <input id="test" type="test">.`

**Component Improvements**
- [ ] Include the Component name/reference (e.g., `component.toString()`) so that it is clear who the offender was
  - [ ] Provide hook to break on a specific violation

**Acceptance Test Improvements**
- [x] For Acceptance Test audits, specify the run number of the audit
  - [x] Provide hook to break on a specified run number to aid in debugging

**Comment by nathanhammond** [comment]
Closed as part of the migration to [ember-a11y-testing](https://github.com/trentmwillis/ember-a11y-testing).
